from pathlib import Path
from types import ModuleType
from typing import Any

DEFAULT_GENERATED_MODULE: str

class ProtoNamespace:
    module_name: str
    module: ModuleType | None
    load_error: Exception | None
    @property
    def loaded(self) -> bool: ...
    def require(self) -> ModuleType: ...
    def has(self, name: str) -> bool: ...
    def get(self, name: str, default: Any = ...) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

def load_proto(module_name: str = DEFAULT_GENERATED_MODULE) -> ProtoNamespace: ...
def loadProto(module_name: str = DEFAULT_GENERATED_MODULE) -> ProtoNamespace: ...
def proto_schema_path() -> Path: ...

proto: ProtoNamespace
