import importlib
import sys

from .auth import (
    AccountSettings,
    AuthenticationCreds,
    AuthenticationState,
    KeyPair,
    LIDMapping,
    LTHashMapValue,
    LTHashState,
    ProtocolAddress,
    SignalAuthState,
    SignalCreds,
    SignalDataSet,
    SignalIdentity,
    SignalKeyStore,
    SignalKeyStoreWithTransaction,
    SignedKeyPair,
)
from .business import (
    BusinessCatalogInput,
    BusinessCollectionsInput,
    BusinessCoverPhotoRemoveInput,
    BusinessCoverPhotoUpdateInput,
    BusinessHoursConfig,
    BusinessHoursOpen,
    BusinessHoursSpecific,
    BusinessOrderDetailsInput,
    BusinessProductCreateInput,
    BusinessProductDeleteInput,
    BusinessProductUpdateInput,
    BusinessProfileInput,
    BusinessProfileUpdateInput,
    DayOfWeekBusiness,
    HoursDay,
    QuickReplyAction,
    UpdateBusinessProfileProps,
)
from .chat import (
    ALL_WA_PATCH_NAMES,
    ArchiveChatInput,
    BlockStatusInput,
    BotListInfo,
    CallLinkCreateInput,
    ChatLabelInput,
    Chat,
    ChatModifyInput,
    ChatModification,
    ChatMutation,
    ChatUpdate,
    CleanDirtyBitsInput,
    ContactRemoveInput,
    ContactUpsertInput,
    DisableLinkPreviewsPrivacyInput,
    FetchManyJidsInput,
    InitialAppStateSyncOptions,
    InitialReceivedChatsState,
    LabelUpsertInput,
    MarkReadInput,
    MessageLabelInput,
    MuteChatInput,
    OnWhatsAppInput,
    PnFromLidUSyncInput,
    PresenceSubscribeInput,
    PresenceUpdateInput,
    PresenceData,
    ProfileNameInput,
    ProfilePictureRemoveInput,
    ProfilePictureUpdateInput,
    ProfilePictureUrlInput,
    ProfileStatusInput,
    QuickReplyRemoveInput,
    QuickReplyUpsertInput,
    StarMessagesInput,
    WAPatchCreate,
    WAPatchName,
    WAPresence,
    WAPrivacyCallValue,
    WAPrivacyGroupAddValue,
    WAPrivacyMessagesValue,
    WAPrivacyOnlineValue,
    WAPrivacyValue,
    WAReadReceiptsValue,
)
from .call import WACallEvent, WACallUpdateType
from .common import (
    CurveKeyPair,
    DisconnectReason,
    WABusinessHours,
    WABusinessHoursConfig,
    WABusinessProfile,
    WAInitResponse,
)
from .community import (
    CommunityAcceptInviteInput,
    CommunityAcceptInviteV4Input,
    CommunityCreateGroupInput,
    CommunityCreateInput,
    CommunityDescriptionUpdateInput,
    CommunityFetchLinkedGroupsInput,
    CommunityInviteCodeInput,
    CommunityInviteInfoInput,
    CommunityJoinApprovalModeInput,
    CommunityLeaveInput,
    CommunityLinkGroupInput,
    CommunityMemberAddModeInput,
    CommunityParticipantsUpdateInput,
    CommunityRequestParticipantsUpdateInput,
    CommunityRevokeInviteInput,
    CommunityRevokeInviteV4Input,
    CommunitySettingUpdateInput,
    CommunitySubjectUpdateInput,
    CommunityToggleEphemeralInput,
    CommunityUnlinkGroupInput,
)
from .contact import Contact
from .events import BaileysEventEmitter, BaileysEventMap, BufferedEventData, LidMappingUpdate
from .identity import IdentityResolveResult, JidAlias, JidKind, MessageIdentityView, SendMessageInput, SendTextInput, UserRef
from .group_metadata import (
    GroupCreateInput,
    GroupDescriptionUpdateInput,
    GroupJoinApprovalModeInput,
    GroupMetadata,
    GroupMemberAddModeInput,
    GroupModificationResponse,
    GroupParticipant,
    GroupParticipantsUpdateInput,
    GroupRequestParticipantsUpdateInput,
    GroupSettingUpdateInput,
    GroupSubjectUpdateInput,
    GroupToggleEphemeralInput,
    ParticipantAction,
    RequestJoinAction,
    RequestJoinMethod,
    WAGroupCreateResponse,
)
from .label import Label, LabelActionBody, LabelColor
from .label_association import (
    ChatLabelAssociation,
    ChatLabelAssociationActionBody,
    LabelAssociation,
    LabelAssociationType,
    LabelAssociationTypes,
    MessageLabelAssociation,
    MessageLabelAssociationActionBody,
)
from .message import (
    AnyMessageContent,
    AnyRegularMessageContent,
    DownloadableMessage,
    MediaConnInfo,
    MessageReceiptType,
    MessageType,
    MessageUpsertType,
    MessageUserReceipt,
    MessageUserReceiptUpdate,
    WAMessageStatus,
    WAMessageStubType,
    MinimalMessage,
    WAContextInfo,
    WAContactMessage,
    WAContactsArrayMessage,
    WAGenericMediaMessage,
    WALocationMessage,
    WAMediaUpload,
    WAMessage,
    WAMessageAddressingMode,
    WAMessageContent,
    WAMessageCursor,
    WAMessageKey,
    WAMessageUpdate,
    WATextMessage,
    WAUrlInfo,
)
from .newsletter import (
    NewsletterChangeOwnerInput,
    NewsletterCreateInput,
    NewsletterCreateResponse,
    NewsletterDemoteInput,
    NewsletterDescriptionUpdateInput,
    NewsletterFetchMessagesInput,
    NewsletterJidInput,
    NewsletterMetadata,
    NewsletterMetadataInput,
    NewsletterNameUpdateInput,
    NewsletterPictureUpdateInput,
    NewsletterReactInput,
    NewsletterUpdate,
    NewsletterUpdateInput,
    NewsletterViewRole,
    QueryIds,
    XWAPaths,
)
from .product import (
    CatalogCollection,
    CatalogCursor,
    CatalogResult,
    CatalogStatus,
    GetCatalogOptions,
    OrderDetails,
    OrderPrice,
    OrderProduct,
    Product,
    ProductAvailability,
    ProductBase,
    ProductCreate,
    ProductCreateResult,
    ProductUpdate,
)
from .signal import (
    DecryptGroupSignalOpts,
    DecryptSignalProtoOpts,
    E2ESession,
    E2ESessionOpts,
    EncryptGroupMessageOpts,
    EncryptMessageOpts,
    PreKey,
    ProcessSenderKeyDistributionMessageOpts,
    SignalRepository,
    SignalRepositoryWithLIDStore,
    SignedPreKey,
)
from .socket import SocketConfig, TransactionCapabilityOptions, WABrowserDescription, WAVersion
from .state import ConnectionState, SyncState, WAConnectionState
from .usync import USyncQueryProtocol

_COMPAT_MODULE_ALIASES = {
    "Auth": "auth",
    "Business": "business",
    "Bussines": "business",
    "Community": "community",
    "Call": "call",
    "Chat": "chat",
    "Contact": "contact",
    "Events": "events",
    "GroupMetadata": "group_metadata",
    "Label": "label",
    "LabelAssociation": "label_association",
    "Message": "message",
    "Newsletter": "newsletter",
    "Product": "product",
    "Signal": "signal",
    "Socket": "socket",
    "State": "state",
    "USync": "usync",
}
for _alias, _target in _COMPAT_MODULE_ALIASES.items():
    _target_mod = f"{__name__}.{_target}"
    _alias_mod = f"{__name__}.{_alias}"
    _loaded = sys.modules.get(_target_mod)
    if _loaded is None:
        try:
            _loaded = importlib.import_module(_target_mod)
        except Exception:
            _loaded = None
    if _loaded is not None:
        sys.modules.setdefault(_alias_mod, _loaded)

__all__ = [
    "AccountSettings",
    "AuthenticationCreds",
    "AuthenticationState",
    "ProtocolAddress",
    "SignalCreds",
    "SignalAuthState",
    "LIDMapping",
    "LTHashMapValue",
    "LTHashState",
    "BusinessHoursConfig",
    "BusinessHoursOpen",
    "BusinessHoursSpecific",
    "BusinessProfileInput",
    "BusinessProfileUpdateInput",
    "BusinessCoverPhotoUpdateInput",
    "BusinessCoverPhotoRemoveInput",
    "BusinessCatalogInput",
    "BusinessCollectionsInput",
    "BusinessOrderDetailsInput",
    "BusinessProductUpdateInput",
    "BusinessProductCreateInput",
    "BusinessProductDeleteInput",
    "DayOfWeekBusiness",
    "HoursDay",
    "QuickReplyAction",
    "UpdateBusinessProfileProps",
    "ALL_WA_PATCH_NAMES",
    "ArchiveChatInput",
    "BlockStatusInput",
    "BotListInfo",
    "CallLinkCreateInput",
    "ChatLabelInput",
    "Chat",
    "ChatModifyInput",
    "ChatModification",
    "ChatMutation",
    "ChatUpdate",
    "CleanDirtyBitsInput",
    "ContactRemoveInput",
    "ContactUpsertInput",
    "DisableLinkPreviewsPrivacyInput",
    "FetchManyJidsInput",
    "InitialAppStateSyncOptions",
    "InitialReceivedChatsState",
    "LabelUpsertInput",
    "MarkReadInput",
    "MessageLabelInput",
    "MuteChatInput",
    "OnWhatsAppInput",
    "PnFromLidUSyncInput",
    "PresenceSubscribeInput",
    "PresenceUpdateInput",
    "PresenceData",
    "ProfileNameInput",
    "ProfilePictureRemoveInput",
    "ProfilePictureUpdateInput",
    "ProfilePictureUrlInput",
    "ProfileStatusInput",
    "QuickReplyRemoveInput",
    "QuickReplyUpsertInput",
    "StarMessagesInput",
    "WAPatchCreate",
    "WAPatchName",
    "WAPresence",
    "WAPrivacyCallValue",
    "WAPrivacyGroupAddValue",
    "WAPrivacyMessagesValue",
    "WAPrivacyOnlineValue",
    "WAPrivacyValue",
    "WAReadReceiptsValue",
    "WACallEvent",
    "WACallUpdateType",
    "CurveKeyPair",
    "DisconnectReason",
    "WABusinessHours",
    "WABusinessHoursConfig",
    "WABusinessProfile",
    "WAInitResponse",
    "CommunityCreateInput",
    "CommunityCreateGroupInput",
    "CommunityLeaveInput",
    "CommunitySubjectUpdateInput",
    "CommunityLinkGroupInput",
    "CommunityUnlinkGroupInput",
    "CommunityFetchLinkedGroupsInput",
    "CommunityRequestParticipantsUpdateInput",
    "CommunityParticipantsUpdateInput",
    "CommunityDescriptionUpdateInput",
    "CommunityInviteCodeInput",
    "CommunityRevokeInviteInput",
    "CommunityAcceptInviteInput",
    "CommunityRevokeInviteV4Input",
    "CommunityAcceptInviteV4Input",
    "CommunityInviteInfoInput",
    "CommunityToggleEphemeralInput",
    "CommunitySettingUpdateInput",
    "CommunityMemberAddModeInput",
    "CommunityJoinApprovalModeInput",
    "Contact",
    "BaileysEventEmitter",
    "BaileysEventMap",
    "BufferedEventData",
    "LidMappingUpdate",
    "JidKind",
    "JidAlias",
    "UserRef",
    "IdentityResolveResult",
    "MessageIdentityView",
    "SendMessageInput",
    "SendTextInput",
    "GroupMetadata",
    "GroupCreateInput",
    "GroupParticipantsUpdateInput",
    "GroupRequestParticipantsUpdateInput",
    "GroupSubjectUpdateInput",
    "GroupDescriptionUpdateInput",
    "GroupSettingUpdateInput",
    "GroupMemberAddModeInput",
    "GroupJoinApprovalModeInput",
    "GroupToggleEphemeralInput",
    "GroupModificationResponse",
    "GroupParticipant",
    "ParticipantAction",
    "RequestJoinAction",
    "RequestJoinMethod",
    "WAGroupCreateResponse",
    "Label",
    "LabelActionBody",
    "LabelColor",
    "ChatLabelAssociation",
    "ChatLabelAssociationActionBody",
    "LabelAssociation",
    "LabelAssociationType",
    "LabelAssociationTypes",
    "MessageLabelAssociation",
    "MessageLabelAssociationActionBody",
    "AnyMessageContent",
    "AnyRegularMessageContent",
    "DownloadableMessage",
    "MediaConnInfo",
    "MessageReceiptType",
    "MessageType",
    "MessageUpsertType",
    "MessageUserReceipt",
    "MessageUserReceiptUpdate",
    "WAMessageStatus",
    "WAMessageStubType",
    "MinimalMessage",
    "WAContextInfo",
    "WAContactMessage",
    "WAContactsArrayMessage",
    "WAGenericMediaMessage",
    "WALocationMessage",
    "WAMediaUpload",
    "WAMessage",
    "WAMessageAddressingMode",
    "WAMessageContent",
    "WAMessageCursor",
    "WAMessageKey",
    "WAMessageUpdate",
    "WATextMessage",
    "WAUrlInfo",
    "NewsletterCreateResponse",
    "NewsletterCreateInput",
    "NewsletterMetadata",
    "NewsletterUpdate",
    "NewsletterUpdateInput",
    "NewsletterJidInput",
    "NewsletterMetadataInput",
    "NewsletterNameUpdateInput",
    "NewsletterDescriptionUpdateInput",
    "NewsletterPictureUpdateInput",
    "NewsletterReactInput",
    "NewsletterFetchMessagesInput",
    "NewsletterChangeOwnerInput",
    "NewsletterDemoteInput",
    "NewsletterViewRole",
    "QueryIds",
    "XWAPaths",
    "CatalogCollection",
    "CatalogCursor",
    "CatalogResult",
    "CatalogStatus",
    "GetCatalogOptions",
    "OrderDetails",
    "OrderPrice",
    "OrderProduct",
    "Product",
    "ProductAvailability",
    "ProductBase",
    "ProductCreate",
    "ProductCreateResult",
    "ProductUpdate",
    "DecryptGroupSignalOpts",
    "DecryptSignalProtoOpts",
    "E2ESession",
    "E2ESessionOpts",
    "EncryptGroupMessageOpts",
    "EncryptMessageOpts",
    "PreKey",
    "ProcessSenderKeyDistributionMessageOpts",
    "SignalRepository",
    "SignalRepositoryWithLIDStore",
    "SignedPreKey",
    "KeyPair",
    "SignalDataSet",
    "SignalIdentity",
    "SignalKeyStore",
    "SignalKeyStoreWithTransaction",
    "SignedKeyPair",
    "SocketConfig",
    "TransactionCapabilityOptions",
    "WABrowserDescription",
    "WAVersion",
    "ConnectionState",
    "SyncState",
    "WAConnectionState",
    "USyncQueryProtocol",
]
